### ISSUE TITLE
All of the classes in this program should be a single class

### ISSUE THREAD

**Issue by sethcenterbar** [BlueLovin/CokeMachine#1]
All of the items in this CokeMachine are really of a single type, 'soda'. They should have attributes of name and price. I think the program would greatly benefit from this refactor.

**Comment by sethcenterbar** [comment]
@BlueLovin based on your implementation, you may want to store the color you want to use on the console as an attribute in the soda class as well.

**Comment by BlueLovin** [comment]
All soda values are now in one class.
